version: '3.8'
services:
  nginx:
    image: nginx:1.25.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - fastapi
    restart: unless-stopped

  fastapi:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=irtsu
      - DB_PASS=irtsu_meteostation
      - DB_NAME=project
      - DB_PORT=49155
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16.3
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_USER=irtsu
      - POSTGRES_PASSWORD=irtsu_meteostation
      - POSTGRES_DB=project
    ports:
      - "49155:49155"
    restart: unless-stopped

volumes:
  db_data:
